pages:
  script:
    - curl -L https://github.com/getzola/zola/releases/download/$ZOLA_VERSION/zola-$ZOLA_VERSION-x86_64-unknown-linux-gnu.tar.gz > zola.tar.gz
    - tar -xzf zola.tar.gz
    - ./zola build

  artifacts:
    paths:
      - public

  only:
    - master

variables:
  ZOLA_VERSION: "v0.8.0"
