base_url = "charlie.hornsby.fi"

title = "Charlie's Corner"
description = ""

default_language = "en"

highlight_code = true
highlight_theme = "base16-ocean-dark"

generate_rss = true

compile_sass = true
